// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_etwwbppvbu2zIx0eWsXWz0ifqWeY_6g',
    appId: '1:425860621066:web:872ecaedf4e583de2850f3',
    messagingSenderId: '425860621066',
    projectId: 'app-flutter-camera',
    authDomain: 'app-flutter-camera.firebaseapp.com',
    storageBucket: 'app-flutter-camera.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqa_nZ-ndeJ10FTY-qV7_Ux0h4oIOrYns',
    appId: '1:425860621066:android:7dd11f10828b9fbf2850f3',
    messagingSenderId: '425860621066',
    projectId: 'app-flutter-camera',
    storageBucket: 'app-flutter-camera.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOEROI_gXKpd-8sU164YTr47OboiNFIX4',
    appId: '1:425860621066:ios:ca3e6cd4b31656642850f3',
    messagingSenderId: '425860621066',
    projectId: 'app-flutter-camera',
    storageBucket: 'app-flutter-camera.appspot.com',
    iosBundleId: 'com.example.flutterAppCamera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOEROI_gXKpd-8sU164YTr47OboiNFIX4',
    appId: '1:425860621066:ios:05a12923a00669d82850f3',
    messagingSenderId: '425860621066',
    projectId: 'app-flutter-camera',
    storageBucket: 'app-flutter-camera.appspot.com',
    iosBundleId: 'com.example.flutterAppCamera.RunnerTests',
  );
}
